USE DB_FEIRA_LIVRE
GO
CREATE TABLE TB_FEIRA (
	ID INT NOT NULL IDENTITY(1,1),
	LONG INT NOT NULL,
	LAT INT NOT NULL,
	SETCENS BIGINT NOT NULL,
	AREAP BIGINT NOT NULL,
	CODDIST TINYINT NOT NULL,
	DISTRITO VARCHAR(100) NOT NULL,
	CODSUBPREF TINYINT NOT NULL,
	SUBPREFE VARCHAR(100) NOT NULL,
	REGIAO5 VARCHAR(5) NOT NULL,
	REGIAO8  VARCHAR(5) NOT NULL,
	NOME_FEIRA VARCHAR(100) NOT NULL,
	REGISTRO VARCHAR(10) NOT NULL,
	LOGRADOURO  VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	REFERENCIA VARCHAR(100),
	CONSTRAINT PK_FEIRA PRIMARY KEY (ID)
)
GO
CREATE INDEX IDX_CONSULTA_FEIRA ON TB_FEIRA (DISTRITO,REGIAO5,NOME_FEIRA,BAIRRO);

