USE DB_FEIRA_LIVRE
GO
CREATE TABLE TB_DISTRITO (
	ID INT NOT NULL  IDENTITY(1,1),
	DISTRITO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_DISTRITO PRIMARY KEY (ID)
)
GO
CREATE TABLE TB_SUB_PREFEITURA (
	ID INT NOT NULL  IDENTITY(1,1),
	SUBPREFE VARCHAR(100) NOT NULL,
	CONSTRAINT PK_SUBPREFEITURA PRIMARY KEY (ID)
)

GO
CREATE TABLE TB_FEIRA (
	ID INT NOT NULL IDENTITY(1,1),
	LONG INT NOT NULL,
	LAT INT NOT NULL,
	SETCENS BIGINT NOT NULL,
	AREAP BIGINT NOT NULL,
	CODDIST INT NOT NULL,	
	CODSUBPREF INT NOT NULL,	
	REGIAO5 VARCHAR(10) NOT NULL,
	REGIAO8  VARCHAR(10) NOT NULL,
	NOME_FEIRA VARCHAR(100) NOT NULL,
	REGISTRO VARCHAR(10) NOT NULL,
	LOGRADOURO  VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	REFERENCIA VARCHAR(100),
	CONSTRAINT PK_FEIRA PRIMARY KEY (ID),
	CONSTRAINT FK_DISTRITO FOREIGN KEY (CODDIST) REFERENCES TB_DISTRITO(ID),
	CONSTRAINT FK_SUB_PREFEITURA FOREIGN KEY (CODSUBPREF) REFERENCES TB_SUB_PREFEITURA(ID)
)

GO
CREATE INDEX IDX_CONSULTA_FEIRA ON TB_FEIRA (REGIAO5,NOME_FEIRA,BAIRRO);

