USE [DB_FEIRA_LIVRE]
GO
SET IDENTITY_INSERT [dbo].[TB_DISTRITO] ON
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (1, N'AGUA RASA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (2, N'ALTO DE PINHEIROS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (3, N'ANHANGUERA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (4, N'ARICANDUVA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (5, N'ARTUR ALVIM')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (6, N'BARRA FUNDA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (7, N'BELA VISTA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (8, N'BELEM')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (9, N'BOM RETIRO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (10, N'BRAS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (11, N'BRASILANDIA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (12, N'BUTANTA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (13, N'CACHOEIRINHA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (14, N'CAMBUCI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (15, N'CAMPO BELO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (16, N'CAMPO GRANDE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (17, N'CAMPO LIMPO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (18, N'CANGAIBA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (19, N'CAPAO REDONDO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (20, N'CARRAO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (21, N'CASA VERDE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (22, N'CIDADE ADEMAR')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (23, N'CIDADE DUTRA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (24, N'CIDADE LIDER')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (25, N'CIDADE TIRADENTES')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (26, N'CONSOLACAO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (27, N'CURSINO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (28, N'ERMELINO MATARAZZO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (29, N'FREGUESIA DO O')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (30, N'GRAJAU')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (31, N'GUAIANASES')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (32, N'IGUATEMI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (33, N'IPIRANGA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (34, N'ITAIM BIBI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (35, N'ITAIM PAULISTA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (36, N'ITAQUERA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (37, N'JABAQUARA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (38, N'JACANA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (39, N'JAGUARA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (40, N'JAGUARE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (41, N'JARAGUA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (42, N'JARDIM ANGELA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (43, N'JARDIM HELENA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (44, N'JARDIM PAULISTA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (45, N'JARDIM SAO LUIS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (46, N'JOSE BONIFACIO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (47, N'LAJEADO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (48, N'LAPA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (49, N'LIBERDADE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (50, N'LIMAO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (51, N'MANDAQUI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (53, N'MOEMA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (54, N'MOOCA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (55, N'MORUMBI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (56, N'PARELHEIROS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (57, N'PARI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (58, N'PARQUE DO CARMO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (59, N'PEDREIRA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (60, N'PENHA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (61, N'PERDIZES')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (62, N'PERUS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (63, N'PINHEIROS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (64, N'PIRITUBA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (65, N'PONTE RASA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (66, N'RAPOSO TAVARES')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (67, N'REPUBLICA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (68, N'RIO PEQUENO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (69, N'SACOMA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (70, N'SANTA CECILIA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (71, N'SANTANA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (72, N'SANTO AMARO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (73, N'SAO DOMINGOS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (74, N'SAO LUCAS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (75, N'SAO MATEUS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (76, N'SAO MIGUEL')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (77, N'SAO RAFAEL')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (78, N'SAPOPEMBA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (79, N'SAUDE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (80, N'SE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (81, N'SOCORRO')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (82, N'TATUAPE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (83, N'TREMEMBE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (84, N'TUCURUVI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (85, N'VILA ANDRADE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (86, N'VILA CURUCA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (87, N'VILA FORMOSA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (88, N'VILA GUILHERME')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (89, N'VILA JACUI')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (90, N'VILA LEOPOLDINA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (91, N'VILA MARIA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (92, N'VILA MARIANA')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (93, N'VILA MATILDE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (94, N'VILA MEDEIROS')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (95, N'VILA PRUDENTE')
GO
INSERT [dbo].[TB_DISTRITO] ([ID], [DISTRITO]) VALUES (96, N'VILA SONIA')
GO
SET IDENTITY_INSERT [dbo].[TB_DISTRITO] OFF
GO

