USE [DB_FEIRA_LIVRE]
GO
SET IDENTITY_INSERT [dbo].[TB_SUB_PREFEITURA] ON
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (1, N'PERUS')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (2, N'PIRITUBA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (3, N'FREGUESIA-BRASILANDIA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (4, N'CASA VERDE-CACHOEIRINHA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (5, N'SANTANA-TUCURUVI')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (6, N'JACANA-TREMEMBE')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (7, N'VILA MARIA-VILA GUILHERME')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (8, N'LAPA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (9, N'SE')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (10, N'BUTANTA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (11, N'PINHEIROS')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (12, N'VILA MARIANA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (13, N'IPIRANGA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (14, N'SANTO AMARO')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (15, N'JABAQUARA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (16, N'CIDADE ADEMAR')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (17, N'CAMPO LIMPO')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (18, N'M''BOI MIRIM')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (19, N'CAPELA DO SOCORRO')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (20, N'PARELHEIROS')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (21, N'PENHA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (22, N'ERMELINO MATARAZZO')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (23, N'SAO MIGUEL')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (24, N'ITAIM PAULISTA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (25, N'MOOCA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (26, N'ARICANDUVA-FORMOSA-CARRAO')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (27, N'ITAQUERA')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (28, N'GUAIANASES')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (29, N'VILA PRUDENTE')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (30, N'SAO MATEUS')
GO
INSERT [dbo].[TB_SUB_PREFEITURA] ([ID], [SUBPREFE]) VALUES (31, N'CIDADE TIRADENTES')
GO
SET IDENTITY_INSERT [dbo].[TB_SUB_PREFEITURA] OFF
GO
